//***********************************************************************************************************
//*                                         *ASCIILogosGen.js*                                              *
//*                 This JS file generates the figlet logos which are shown in the startup of the game      *
//*                                                                                                         *
//*                 WORKING: It exports the logos in a java enum, located in                                *
//*                            ../java/com/ludus/ASCIILogos.java                                            *
//*                          The output is shown in the console and then piped to the file,which is deleted *
//*                          before to prevent appending to itself.                                         *
//*                                                                                                         *
//*                 LIBRARIES: uses the figlet.js library, link: https://github.com/patorjk/figlet.js       *
//*                                                                                                         *
//*                 Thanks :  Patrick Gillespie(https://github.com/patorjk/) and other contributors :D      *
//*                                                                                                         *
//*                 Run : do npm run genLogos to generate the logos.                                        *
//***********************************************************************************************************


var figlet = require('figlet');

var header = `package com.ludus;

//*******************************************************************************************
//*                         *AsciiLogos.java*                                               *
//*             ⚠ ⚠       !! DO NOT EDIT THIS FILE !!     ⚠⚠                                *
//*     This file is AUTOMATICALLY GENERATED by ASCIILogoGen/ASCIILogosGen.js               *
//*     please see the aforementioned file to edit this code!!                              *
//*     This is an enum containing the ascii logos shown in                                 *
//*     the startup of the game.                                                            *
//*                                                                                         *
//*     source : https://www.patorjk.com/software/taag/#p=testall&font=Wet%20Letter&t=ludus *
//*                                                                                         *
//*                                                     ~ Generated from ASCIILogosGen.js   *
//*******************************************************************************************


import java.util.Random;

public enum ASCIILogos{
`;



var enumEnd = `
    private final String logo;
    ASCIILogos(String logo){
        this.logo = logo;
    }
    public String getVal() {
        return  logo;
    }
    public static String getRand(){
        return  com.ludus.ASCIILogos.values()[new Random().nextInt(289/*(ASCIILogos.values().length)*/)].getVal();
    }
}
`;



// print the initial Code of the file
console.log(header);
//print the fonts,as Java enum values:

figlet.fonts(
  	function(err, fonts) {
   		if (err) {
   			console.log('Some Error Occurred While loading the fonts:');
   			console.dir(err);
   			return;
   		}
   		fonts.forEach(
   			function(font){
   				figlet.text('Ludus', {
   					font: font,
   					horizontalLayout: 'default',
   					verticalLayout: 'default',
				    width: 180,
			    	whitespaceBreak: true
		    	},
	    			function(err, data) {
    					if (err) {
   							console.log('Something went wrong While using the fonts');
						    console.dir(err);
					    	return;
				    	}

				        var varName = font.toString().toUpperCase().replace(/ /g,"_").replace(/3/g,"THREE").replace(/4/g,"FOUR").replace(/2/g,"TWO").replace(/1/g,"ONE").replace(/6/g,"SIX").replace(/5/g,"FIVE")/* some fonts start with numbers :( */ .replace(/-/g,"_").replace(/\'/g,""); //some have - :( the /g is regex for replace all occurences, apparently js has native regex syntax?

				    	var varVal = data.toString().replace(/\\/g,"\\\\").replace(/\"/g , "\\\"");

                        var valSeparator = ","

			    		if(varName == "MNEMONIC") valSeparator = ";" //if it is the final font,end with a semicolon.

			    		var finalString ="\t\t\t" + varName + "(\"\"\"\n" + varVal + "\n \"\"\")"+valSeparator+"\n\n";

		    			console.log(finalString);

		    			});
    		});
   	});


// wait for the figlet.js to print all the logos and then print the ending of the enum.

const timer = ms => new Promise( res => setTimeout(res, ms));
timer(3000).then(_=>console.log(enumEnd));      // should take abt 3 seconds.
